### PR TITLE
Remove makefile mess

### PR DESCRIPTION
**Pull request by KenwoodFox**
This PR cleans up and removes all the makefile stuff i gave you before, you should review it and merge it only if you think it actually does its job :3 ur the best

### CODE REVIEW

**Review by Amoskeag — COMMENTED** [review]
Looks great

**Comment by KenwoodFox** [comment]
Lets merge this thanks

**Review by Amoskeag — COMMENTED** [review]
Great job!

**Review by Amoskeag — APPROVED** [review]
Looks great!

**Pull request merged**
